# version: "3.9"

# services:

#   mongo_backend:

#     build:
#       context: .
#       dockerfile: Backend/Dockerfile
#     ports:
#       - "8001:8001"
#     container_name: mongo_backend


version: "3.9"

services:
  mongo_backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "8001:8001"
    container_name: mongo_backend
<<<<<<< HEAD
#     depends_on:
#       - MongoDB_service   

#   MongoDB_service:
#     image: mongo:6.0
#     container_name: MongoDB_service
#     restart: always
#     ports:
#       - "27017:27017"   
#     volumes:
#       - mongodb_data:/data/db  

# volumes:
#   mongodb_data:
=======
    depends_on:
      - MongoDB_service   

  MongoDB_service:
    image: mongo:6.0
    container_name: MongoDB_service
    restart: always
    ports:
      - "27017:27017"   
    volumes:
      - mongodb_data:/data/db  

volumes:
  mongodb_data:
>>>>>>> 45dc35ffc74f5a0a9ec25708434053465bbe3cda
